blueprint:
  name: Aqara Z1 Pro (MQTT Topic Version)
  description: >
    Controls Aqara Z1 Pro Switches directly via MQTT Topic (Bypasses missing sensors).
    
    1. Verify your device name in Zigbee2MQTT (e.g. "Kitchen Livng room").
    2. Enter "zigbee2mqtt/[DEVICE_NAME]" in the topic field below.
    3. Ensure buttons are in 'decoupled' mode in Z2M settings.
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: The full topic path (e.g. zigbee2mqtt/Kitchen Livng room)
      default: "zigbee2mqtt/Kitchen Livng room"
    
    # --- TOP BUTTON ---
    single_top:
      name: Top - Single Click
      default: []
      selector: { action: {} }
    double_top:
      name: Top - Double Click
      default: []
      selector: { action: {} }
    hold_top:
      name: Top - Hold
      default: []
      selector: { action: {} }

    # --- CENTER BUTTON ---
    single_center:
      name: Center - Single Click
      default: []
      selector: { action: {} }
    double_center:
      name: Center - Double Click
      default: []
      selector: { action: {} }
    hold_center:
      name: Center - Hold
      default: []
      selector: { action: {} }

    # --- BOTTOM BUTTON ---
    single_bottom:
      name: Bottom - Single Click
      default: []
      selector: { action: {} }
    double_bottom:
      name: Bottom - Double Click
      default: []
      selector: { action: {} }
    hold_bottom:
      name: Bottom - Hold
      default: []
      selector: { action: {} }

    # --- 4TH BUTTON (Wireless) ---
    single_4:
      name: 4th Button - Single
      default: []
      selector: { action: {} }
    double_4:
      name: 4th Button - Double
      default: []
      selector: { action: {} }
    hold_4:
      name: 4th Button - Hold
      default: []
      selector: { action: {} }

mode: restart
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

condition:
  - condition: template
    value_template: "{{ trigger.payload_json.action is defined }}"

action:
  - variables:
      cmd: "{{ trigger.payload_json.action }}"
  - choose:
      # TOP MAPPINGS
      - conditions: "{{ cmd == 'single_top' }}"
        sequence: !input single_top
      - conditions: "{{ cmd == 'double_top' }}"
        sequence: !input double_top
      - conditions: "{{ cmd == 'hold_top' }}"
        sequence: !input hold_top

      # CENTER MAPPINGS
      - conditions: "{{ cmd == 'single_center' }}"
        sequence: !input single_center
      - conditions: "{{ cmd == 'double_center' }}"
        sequence: !input double_center
      - conditions: "{{ cmd == 'hold_center' }}"
        sequence: !input hold_center

      # BOTTOM MAPPINGS
      - conditions: "{{ cmd == 'single_bottom' }}"
        sequence: !input single_bottom
      - conditions: "{{ cmd == 'double_bottom' }}"
        sequence: !input double_bottom
      - conditions: "{{ cmd == 'hold_bottom' }}"
        sequence: !input hold_bottom
        
      # 4TH BUTTON
      - conditions: "{{ cmd in ['single_4', '4_single'] }}"
        sequence: !input single_4
      - conditions: "{{ cmd in ['double_4', '4_double'] }}"
        sequence: !input double_4
      - conditions: "{{ cmd in ['hold_4', '4_hold'] }}"
        sequence: !input hold_4
