blueprint:
  name: Aqara Z1 Pro Quadruple (Zigbee2MQTT)
  description: >
    Automate the Aqara Z1 Pro (4-Gang). 
    
    IMPORTANT: You must go to Zigbee2MQTT > Device > Settings (Specific) and set 
    operation_mode to 'decoupled' for the buttons you want to use as triggers.
  domain: automation
  input:
    action_sensor:
      name: Action Sensor
      description: Select the entity ending in "_action" (e.g., sensor.kitchen_switch_action)
      selector:
        entity:
          domain: sensor
          integration: mqtt

    # --- BUTTON 1 (Top / Left) ---
    press_1:
      name: Top/Left - Single Press
      default: []
      selector: { action: {} }
    double_1:
      name: Top/Left - Double Press
      default: []
      selector: { action: {} }
    hold_1:
      name: Top/Left - Hold
      default: []
      selector: { action: {} }

    # --- BUTTON 2 (Center) ---
    press_2:
      name: Center - Single Press
      default: []
      selector: { action: {} }
    double_2:
      name: Center - Double Press
      default: []
      selector: { action: {} }
    hold_2:
      name: Center - Hold
      default: []
      selector: { action: {} }

    # --- BUTTON 3 (Bottom) ---
    press_3:
      name: Bottom - Single Press
      default: []
      selector: { action: {} }
    double_3:
      name: Bottom - Double Press
      default: []
      selector: { action: {} }
    hold_3:
      name: Bottom - Hold
      default: []
      selector: { action: {} }

    # --- BUTTON 4 (Wireless / 4th) ---
    press_4:
      name: 4th Button - Single Press
      default: []
      selector: { action: {} }
    double_4:
      name: 4th Button - Double Press
      default: []
      selector: { action: {} }
    hold_4:
      name: 4th Button - Hold
      default: []
      selector: { action: {} }

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input action_sensor
    attribute: action

action:
  - variables:
      cmd: "{{ trigger.to_state.state }}"
  - choose:
      # TOP / BUTTON 1
      - conditions: "{{ cmd in ['single_top', '1_single'] }}"
        sequence: !input press_1
      - conditions: "{{ cmd in ['double_top', '1_double'] }}"
        sequence: !input double_1
      - conditions: "{{ cmd in ['hold_top', '1_hold'] }}"
        sequence: !input hold_1

      # CENTER / BUTTON 2
      - conditions: "{{ cmd in ['single_center', '2_single'] }}"
        sequence: !input press_2
      - conditions: "{{ cmd in ['double_center', '2_double'] }}"
        sequence: !input double_2
      - conditions: "{{ cmd in ['hold_center', '2_hold'] }}"
        sequence: !input hold_2

      # BOTTOM / BUTTON 3
      - conditions: "{{ cmd in ['single_bottom', '3_single'] }}"
        sequence: !input press_3
      - conditions: "{{ cmd in ['double_bottom', '3_double'] }}"
        sequence: !input double_3
      - conditions: "{{ cmd in ['hold_bottom', '3_hold'] }}"
        sequence: !input hold_3

      # 4TH BUTTON (Wireless)
      - conditions: "{{ cmd in ['single_4', '4_single'] }}"
        sequence: !input press_4
      - conditions: "{{ cmd in ['double_4', '4_double'] }}"
        sequence: !input double_4
      - conditions: "{{ cmd in ['hold_4', '4_hold'] }}"
        sequence: !input hold_4
